### PR TITLE
fix: section overflow on mobile

### LINKED ISSUE #81: Index page sections causes overflow on mobile
CleanShot 2023-02-02 at 12 39 50@2x

### PR DESCRIPTION
**Pull request by Agustina-Carrion**
close #81

### CODE REVIEW

**Comment by tobimori** [comment]
image

check again pls

**Comment by tobimori** [comment]
not cut off correctly now
image

**Comment by pReya** [comment]
@tobimori Can you check again?

**Comment by tobimori** [comment]
Looks good to me now

**Review by tobimori — APPROVED** [review]

**Pull request merged**
