### PR TITLE
feat: interventions

### PR DESCRIPTION
**Pull request by pReya**
- [x] single view 
- [x] index/list view

### CODE REVIEW

**Comment by pReya** [comment]
@tobimori Can you give us feedback/review on the whole "Interventions" home page section and subpage?

Unfortunately some links are not working on the Preview Deployments. So I'm afraid you need to check it out locally :(

**Comment by tobimori** [comment]
Can you add proper hover styles & focus styles to the entries?

Focus -> headline underlines
Hover -> image scaled up similar to news slider on home

**Comment by tobimori** [comment]
Map feedback:
1. Love it!
2. margin-top should be more due to scaling on hover 
CleanShot 2023-02-02 at 12 52 38@2x
3. Whole block should be clickable - including the map pin.

**Comment by pReya** [comment]
@Agustina-Carrion Do you mind tackling the feedback from Tobias?

**Comment by tobimori** [comment]
CleanShot 2023-02-02 at 12 57 36@2x
Aspect ratios for sliders should be consistent across breakpoints, and dynamic to the largest image in height if possible.

**Comment by Agustina-Carrion** [comment]
> Can you add proper hover styles & focus styles to the entries?
> 
> Focus -> headline underlines Hover -> image scaled up similar to news slider on home
> 
> Also, the whole entry should be clickable.
> 
> TODO: [ ] Hover/Focus styles [ ] Make the whole entry clickable. [ ] Check the text sizes on mobile again, they seem to be a bit off and not consistent.

What do you mean by entries? Are these the interventions preview cards? (And i'm referring to the cards that we use at the interventions single view) Just to know where to implement the styling changes (hover and focus)

Text sizes have been checked and edited to keep consistency following your figma design. ✅

**Comment by tobimori** [comment]
> What do you mean by entries? Are these the interventions preview cards?

Exactly. Currently I can only click on the image or "Read more", I want the whole block to be clickable.

**Comment by tobimori** [comment]
CleanShot 2023-02-06 at 16 27 51@2x
margin-top needs to be on the link itself and not the child as otherwise the link is larger than the actual content.

Also please do transform-x instead of transform-y for the hover effect.

**Comment by tobimori** [comment]
Remove outline as focus style as we specify that by ourselves is the last feedback I give. Otherwise, LGTM.

**Comment by pReya** [comment]
> Remove outline as focus style as we specify that by ourselves is the last feedback I give. Otherwise, LGTM.

You mean to remove it globally? Or on some specific elements?

**Comment by tobimori** [comment]
> > Remove outline as focus style as we specify that by ourselves is the last feedback I give. Otherwise, LGTM.
> 
> You mean to remove it globally? Or on some specific elements?

On the article block links as we underline the text when focused.

**Comment by tobimori** [comment]
Sorry, this was a bit confusing.

On the article page, the name gets an underline when focused + outline.
CleanShot 2023-02-11 at 10 00 35@2x

On the interventions page, it's just outlined. 

CleanShot 2023-02-11 at 10 01 32@2x

We should make sure this behavior matches overall.

**Pull request merged**
