### PR TITLE
feat: update homepage

### LINKED ISSUE #26: Home Page Redesign first part
https://www.figma.com/file/AgmKq22D5pemIGu4vswTh8/%F0%9F%8C%B2-Tolocar?node-id=946%3A1016&t=n08BUlA885Q7VduE-0

- [ ] "Our Impact" section
- [ ] "Community" section

### PR DESCRIPTION
**Pull request by Agustina-Carrion**
closes #26

### CODE REVIEW

**Review by pReya — CHANGES_REQUESTED** [review]
Screenshot 2023-01-23 at 18 31 03

Can you fix the line-height for the `large` variant of the `HeadlineUnderlined`?

**Review by pReya — CHANGES_REQUESTED** [review]
Screenshot 2023-01-23 at 18 47 35

Another background image running away from the content-width

**Comment by Agustina-Carrion** [comment]
> Screenshot 2023-01-23 at 18 31 03
> 
> Can you fix the line-height for the `large` variant of the `HeadlineUnderlined`?

I've fixed the line-height, and i tried to scale-x for making it shorter on the mobile viewport. But before going to two lines, it's scaled to the shorter version which looks a bit odd for a couple of width px. I'm not sure how to solve... Try resizing and let me know if it's visually problematic.

**Comment by Agustina-Carrion** [comment]
> Screenshot 2023-01-23 at 18 47 35
> 
> Another background image running away from the content-width

Fixed a bit differently than other cases. Not fully aligned like figma due to the general styling of the container-width div. If need be, i'll work on it again tomorrow to get it to work as it did before.

**Comment by pReya** [comment]
The "what we do" section has been slightly updated in Figma. @Agustina-Carrion Can you include the latest changes?

**Review by pReya — APPROVED** [review]

**Pull request merged**
